### ISSUE TITLE
[PE-D][Tester C] Missing image in User Guide under edit command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T17-1/tp#123] opened 2023-03-31 19:06 UTC
![image.png](https://raw.githubusercontent.com/Sheemo/ped/main/files/6b5c44f2-bebc-4778-83e0-b0a2df4b6abb.png)

There is supposed to be an image there but there is only markdown

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Sheemo/ped#3

**Comment by WillCWX** [comment] 2023-04-01 07:25
duplicate of #134

**Closed by WillCWX** 2023-04-01 07:25 UTC
Labels: duplicate
